version: "3.8"

services:
  ngnix:
    container_name: nginx
    image: nck974/flight-combination-finder-ngnix:1.0.3
    restart: unless-stopped
    depends_on:
      - flightcombinationfinder
      - flightcombinationfinderng
    ports:
      - 443:443
      - 80:80
    environment:
      - NGINX_HOST=${SERVER_IP}
    volumes:
      - ./ssl/:/etc/nginx/ssl/:ro

  flightcombinationfinder:
    container_name: flightcombinationfinder
    image: nck974/flight-combination-finder:1.0.5
    restart: unless-stopped
    depends_on:
      - flightsdatabase
    ports:
      - 8080:8080

  flightcombinationfinderng:
    container_name: flightcombinationfinderng
    image: nck974/flight-combination-finder-ng:1.0.6
    restart: unless-stopped
    depends_on:
      - flightsdatabase
      - flightcombinationfinder
    environment:
      - BACKEND_URL=https://${SERVER_IP}/backend
      - PRODUCTION=true
    ports:
      - 8081:80

  flightsdatabase:
    container_name: flightsdatabase
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flights
      - POSTGRES_PASSWORD=flights
      - POSTGRES_DB=flights
    ports:
      - 5439:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
    name: flightsdatabase
