version: "3.8"

services:
  flight-combinanation-finder:
    container_name: flight-combinanation-finder
    image: nck974/flight-combination-finder:1.0.1
    restart: unless-stopped
    depends_on:
      - flightsdatabase
    ports:
      - 8080:8080

  flight-combinanation-finder-ng:
    container_name: flight-combinanation-finder-ng
    image: nck974/flight-combination-finder-ng:1.0.1
    restart: unless-stopped
    depends_on:
      - flightsdatabase
      - flight-combinanation-finder
    environment:
      - BACKEND_URL=http://${SERVER_IP}:8080/backend
    ports:
      - 8081:80

  flightsdatabase:
    container_name: flightsdatabase
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flights
      - POSTGRES_PASSWORD=flights
      - POSTGRES_DB=flights
    ports:
      - 5439:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
    name: flightsdatabase
