# cd ngnix
# docker build -t nck974/flight-combination-finder-ngnix:1.0.1 .
# docker push nck974/flight-combination-finder-ngnix:1.0.1
FROM nginx:1.25.2
COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl.conf /etc/nginx/conf.d/ssl.conf